source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'YHJTagList_Example' do
  pod 'MRJTagList', :path => '../'
end

target 'YHJTagList_Tests' do
  pod 'MRJTagList', :path => '../'
end
